# Generated by Django 3.2.5 on 2021-07-31 13:00

from django.db import migrations
import projects.models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_rename_lead_imagegallery_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagegallery',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(upload_to=projects.models.upload_to, verbose_name='Image'),
        ),
    ]
